---

- hosts: all
  become: true
  tasks:

  - name: install updates (Ubuntu)
    tags:  apache, apache2, ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:
  - name: install apache and php package for Ubuntu , Fedora
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu", "Fedora"]

- hosts: file_server
  become: true
  tasks:

  - name: install samba and vsftpd packages
    tags: samba, ftp, vsftpd
    apt:
      name:
        - samba
        - vsftpd
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu", "Fedora"]

